version: "3.8"
services:
  app:
    build: .
    container_name: plex_service
    ports:
      - "34200:34200"
    volumes:
      - .:/app
      - ${PATH_VIDEOS}:/Videos
    env_file:
      - .env

  redis:
    image: redis:7.4.1
    container_name: redis_service
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

  worker:
    build: .
    container_name: celery_service
    command: celery -A app.tasks worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis

volumes:
  redis_data: